name: ♻ backend

on:
  workflow_dispatch:
    inputs:
      runs_on:
        description: The label of the runner to use.
        type: string
        required: false
        default: ubuntu-24.04

      environment:
        description: The GitHub environment to use for deployments.
        type: string
        required: true

      terraform_version:
        description: The version of Terraform to install.
        type: string
        required: false
        default: latest

      working_directory:
        description: The directory containing the Terraform configuration.
        type: string
        required: false
        default: "."

      backend_config:
        description: Path to the partial backend configuration file.
        type: string
        required: false
        default: "backend-configs/backend.tfbackend"

      run_terraform_plan:
        description: Run terraform plan?
        type: boolean
        required: false
        default: true

      run_terraform_apply:
        description: Run terraform apply using the saved plan?
        type: boolean
        required: false
        default: true

jobs:
  terraform-plan:
    name: Terraform Plan

    if: ${{ inputs.run_terraform_plan && github.actor != 'dependabot[bot]' }}

    runs-on: ${{ inputs.runs_on }}

    environment:
      name: ${{ inputs.environment }}

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}


    outputs:
      upload-outcome: ${{ steps.upload.outcome }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          if [ -n "${{ inputs.backend_config }}" ]; then
            BACKEND_FILE="${{ inputs.backend_config }}"
          else
            BACKEND_FILE="backend-${{ inputs.environment }}.tfbackend"
          fi

          terraform init \
            -input=false \
            -backend-config="$BACKEND_FILE"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -out=tfplan

      - name: Upload Terraform Plan
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ inputs.working_directory }}/tfplan
          if-no-files-found: error
          retention-days: 1

  terraform-apply:
    name: Terraform Apply

    needs:
      - terraform-plan

    if: >-
      ${{
        inputs.run_terraform_apply &&
        needs.terraform-plan.outputs.upload-outcome == 'success'
      }}

    runs-on: ${{ inputs.runs_on }}

    environment:
      name: ${{ inputs.environment }}

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        env:
          BACKEND_CONFIG: ${{ inputs.backend_config }}
        run: |
          optional_args=()

          if [[ -n "$BACKEND_CONFIG" ]]; then
            optional_args+=("-backend-config=$BACKEND_CONFIG")
          fi

          terraform init \
            -input=false \
            "${optional_args[@]}"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{ inputs.working_directory }}

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan