name: ♻ Backend

on:
  workflow_dispatch:
    inputs:
      runs_on:
        description: Runner to use
        type: string
        required: false
        default: ubuntu-24.04

      environment:
        description: Deployment environment (test/prod)
        type: string
        required: true

      terraform_version:
        description: Terraform version
        type: string
        required: false
        default: latest

      run_terraform_plan:
        description: Run terraform plan
        type: boolean
        required: false
        default: true

      run_terraform_apply:
        description: Run terraform apply
        type: boolean
        required: false
        default: true

      working_directory:
        description: The working directory to run the Terraform commands in.
        type: string
        required: false
        default: "terraform/backend"

jobs:
  terraform-plan:
    name: Terraform Plan

    if: ${{ inputs.run_terraform_plan }}

    runs-on: ${{ inputs.runs_on }}

    environment:
      name: ${{ inputs.environment }}

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    outputs:
      upload-outcome: ${{ steps.upload.outcome }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          BACKEND_FILE="../backend-config/backend-${{ inputs.environment }}.tfbackend"

          echo "Using backend: $BACKEND_FILE"

          terraform init \
            -input=false \
            -backend-config="$BACKEND_FILE"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -out=tfplan

      - name: Upload Terraform Plan
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/backend
          retention-days: 1

  terraform-apply:
    name: Terraform Apply

    needs:
      - terraform-plan

    if: |
      needs.terraform-plan.outputs.upload-outcome == 'success' &&
      inputs.run_terraform_apply

    runs-on: ${{ inputs.runs_on }}

    environment:
      name: ${{ inputs.environment }}

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          BACKEND_FILE="../backend-config/backend-${{ inputs.environment }}.tfbackend"

          terraform init \
            -input=false \
            -backend-config="$BACKEND_FILE"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: terraform/backend

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan