name: Deploy

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      run_terraform_apply:
        description: >
          Run terraform apply after approval
        type: boolean
        required: false
        default: true

jobs:
  a_dev:
    name: 01 Dev
    permissions:
      contents: read
      id-token: write

    uses: ./.github/workflows/terraform.yaml

    with:
      environment: dev
      working_directory: terraform/environment/dev
      backend_config: ../../backend-configs/backend-dev.tfbackend
      run_terraform_apply: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.run_terraform_apply) }}

    secrets: inherit

  b_test:
    name: 02 Test
    permissions:
      contents: read
      id-token: write

    uses: ./.github/workflows/terraform.yaml

    with:
      environment: test
      working_directory: terraform/environment/test
      backend_config: ../../backend-configs/backend-test.tfbackend
      run_terraform_apply: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.run_terraform_apply) }}

    secrets: inherit

  c_prod:
    name: 03 Prod
    permissions:
      contents: read
      id-token: write

    uses: ./.github/workflows/terraform.yaml

    with:
      environment: prod
      working_directory: terraform/environment/prod
      backend_config: ../../backend-configs/backend-prod.tfbackend
      run_terraform_apply: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.run_terraform_apply) }}

    secrets: inherit