name: Deploy

on:
  push:
    branches: [main]
    paths:
      - "terraform/environment/**"
      - "terraform/modules/**"
      - "terraform/backend-configs/**"

  pull_request:
    branches: [main]
    paths:
      - "terraform/environment/**"
      - "terraform/modules/**"

  workflow_dispatch:
    inputs:
      run_terraform_apply:
        description: >
          Run `terraform apply` for the saved plan file, after environment approval?
          On pull requests this is always forced to `false` regardless of this input.
        type: boolean
        required: false
        default: true

jobs:
  terraform:
    name: dev
    permissions:
      contents: read
      id-token: write

    uses: ./.github/workflows/terraform.yaml

    with:
      environment: dev
      working_directory: terraform/environment/dev
      backend_config: ../../backend-configs/backend-dev.tfbackend
      run_terraform_apply: ${{ github.event_name != 'pull_request' && inputs.run_terraform_apply != false }}

    secrets: inherit